apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Initial Deployment"
  creationTimestamp: "2024-02-04T00:42:16Z"
  generation: 1
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
  resourceVersion: "100709"
  uid: 3a9907b7-afde-4439-80db-d9375c66f563
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: currency-conversion
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: currency-conversion
    spec:
      containers:
        - image: panneercts/currency-conversion:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: currency-conversion
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 2Gi
            requests:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 2Gi
          securityContext:
            capabilities:
              drop:
                - NET_RAW
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/arch
          operator: Equal
          value: amd64
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2024-02-04T00:45:14Z"
      lastUpdateTime: "2024-02-04T00:45:14Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2024-02-04T00:42:16Z"
      lastUpdateTime: "2024-02-04T00:45:14Z"
      message: ReplicaSet "currency-conversion-6c78c4c894" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2024-02-04T00:47:15Z"
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
  resourceVersion: "102683"
  uid: e2845827-85bd-4687-b0b5-848b4b4d8a3c
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.227.172
  clusterIPs:
    - 34.118.227.172
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 32491
      port: 8091
      protocol: TCP
      targetPort: 8091
  selector:
    app: currency-conversion
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 34.67.109.206
