server:
  port: 8081
  servlet.context-path: /exchange-service
  error.include-stacktrace: never

spring:
  application.name: exchange-service
  config.import: optional:configserver:http://localhost:8888

logging:
  pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    com.in28min.ms.sbv3: debug
    org.springframework.web: info

management:
  endpoints.web.exposure.include: "*"
  tracing.sampling.probability: 1.0
#  zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans

---
spring:
  h2:
    console.enabled: true
    console.path: /h2-ui
  datasource.url: jdbc:h2:mem:currencydb
  jpa.defer-datasource-initialization: true
  jpa.show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl.defaultZone: http://localhost:8761/eureka