server:
  port: 8091
  servlet.context-path: /conversion-service
  error.include-stacktrace: never

spring:
  application.name: conversion-service
  config.import: optional:configserver:http://localhost:8888

logging:
  pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    com.in28min.ms.sbv3: debug
    org.springframework.web: info

management:
  endpoints.web.exposure.include: "*"
  tracing.sampling.probability: 1.0
#  zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl.defaultZone: http://localhost:8761/eureka
